robocopy clover/sprites ../clovermon-showdown-client/sprites /e
robocopy clover/audio ../clovermon-showdown-client/audio /e
robocopy clover-cap/sprites ../clovermon-showdown-client/sprites /e
robocopy clover-cap/audio ../clovermon-showdown-client/audio /e
robocopy wack/sprites ../clovermon-showdown-client/sprites /e
robocopy wack/audio ../clovermon-showdown-client/audio /e
robocopy sburbmons/sprites ../clovermon-showdown-client/sprites /e
robocopy sweet/sprites ../clovermon-showdown-client/sprites /e
robocopy create-a-blobbos/sprites ../clovermon-showdown-client/sprites /e