cp -R ./clover/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./clover/audio/* ../clovermon-showdown-client/audio/
cp -R ./clover-cap/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./clover-cap/audio/* ../clovermon-showdown-client/audio/
cp -R ./wack/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./wipmons/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./wack/audio/* ../clovermon-showdown-client/audio/
cp -R ./sburbmons/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./sweet/sprites/* ../clovermon-showdown-client/sprites/
cp -R ./create-a-blobbos/sprites/* ../clovermon-showdown-client/sprites/